version: "3.7"

services:
  process-centric-layer:
    build:
      context: ./telegram_bot
    volumes:
      - ./telegram_bot:/app
    command: main.py

  business-layer:
    build:
      context: ./business-layer
    volumes:
      - ./business-layer:/app
    ports:
      - "8084:80"
    command: main.py

  data-layers:
    build:
      context: ./data-layers
    ports:
      - "8083:80"
    command: run start
