version: "3.7"

services:
  process-centric-layer:
    build:
      context: ./process-centric
    volumes:
      - ./process-centric:/app
    command: main.py
    depends_on:
      - business-layer

  business-layer:
    build:
      context: ./business-layer
    volumes:
      - ./business-layer:/app
    ports:
      - "8084:80"
    command: main.py
    depends_on:
      - data-layers

  data-layers:
    build:
      context: ./data-layers
    ports:
      - "8083:80"
    volumes:
      - ./data-layers:/app
      - node_modules:/app/node_modules/
    command: run dev

volumes:
  node_modules: